### ISSUE TITLE
Number of tags

### ISSUE THREAD

**Issue by ikurochkin** [jtprogru/obsidian-vault-full-statistics-plugin#1]
I think the number of tags can also be a useful metric for statistics.

**Comment by jtprogru** [comment]
@ikurochkin see plz this release:

https://github.com/jtprogru/obsidian-vault-full-statistics-plugin/releases/tag/v0.1.0

**Comment by jtprogru** [comment]
Released in https://github.com/jtprogru/obsidian-vault-full-statistics-plugin/releases/tag/1.0.2
